const escape = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]);
const json = value => JSON.stringify(value ?? null, null, 2);
const display = value => typeof value === 'string' ? value : json(value);
const md = value => String(value ?? '').replace(/\s+/g, ' ').replace(/[\\`*_[\]<>#|]/g, '\\$&');
const fence = value => { const content = display(value), delimiter = '`'.repeat(Math.max(3, ...[...content.matchAll(/`+/g)].map(match => match[0].length + 1))); return `${delimiter}\n${content}\n${delimiter}`; };
const cost = value => value.sum === null ? `Unknown (0/${value.planned} attempts)` : `$${value.sum.toFixed(6)} recorded (${value.observed}/${value.planned} attempts${value.complete ? '' : '; incomplete'})`;
const timing = value => value.median === null ? 'Unknown' : `${value.median.toFixed(1)} ms median (${value.observed}/${value.planned} attempts${value.complete ? '' : '; incomplete'})`;
const label = value => value.replaceAll('_', ' ');
const summaryColumns = run => [run.id, run.requestedModel, `${run.summary.quality.pass} pass / ${run.summary.quality.fail} fail / ${run.summary.quality.unscored} unscored / ${run.summary.quality.pending} pending`, `${run.identity.verified}/${run.summary.plannedAttempts} attempts verified`, cost(run.applicationCost), cost(run.summary.judgeCostUsd), timing(run.applicationLatencyMs)];
const headings = ['Run', 'Requested model', 'Recorded checks', 'Model receipts', 'Application task cost', 'Judge cost', 'Task latency'];

export function markdownReport(comparison) {
  const lines = ['# Compare models on the same eval', '', `Baseline: **${md(comparison.baselineId)}**`, '', ...comparison.limitations.map(value => `${value}\n`), '| ' + headings.join(' | ') + ' |', '| ' + headings.map(() => '---').join(' | ') + ' |', ...comparison.runs.map(run => '| ' + summaryColumns(run).map(md).join(' | ') + ' |'), '', 'Application costs above retain spending from failed or fallback-served attempts; those attempts do not establish candidate quality. Per-call coverage is reported separately below.', '', '## Frozen scope', '', fence({ workload: comparison.workload, fingerprint: comparison.fingerprint, criteria: comparison.criteria }), ''];
  for (const run of comparison.runs) lines.push(`## ${md(run.id)}: provenance and coverage`, '', fence({ sourcePath: run.sourcePath, sourceDigest: run.sourceDigest, requestedModel: run.requestedModel, startedAt: run.startedAt, completedAt: run.completedAt, identity: run.identity, calls: run.callEvidence, taskLatency: run.applicationLatencyMs }), '');
  for (const pair of comparison.pairs) {
    lines.push(`## ${md(pair.candidateId)} against ${md(comparison.baselineId)}`, '', fence(pair.counts), '');
    for (const row of pair.rows) {
      const item = comparison.cases.find(value => value.id === row.caseId);
      lines.push(`### ${md(row.title)} — repetition ${row.repetition}: ${label(row.category)}`, '', 'Input:', '', fence(item.input), '', 'Expected:', '', fence(item.expected), '');
      for (const [name, attempt] of [['Baseline', row.baseline], ['Candidate', row.candidate]]) lines.push(`#### ${name}`, '', `Execution: ${md(attempt.executionStatus)}. Checks: ${attempt.quality}. Model identity: ${attempt.identity.status}. ${attempt.identity.reason}`, '', attempt.outputRecorded ? fence(attempt.output) : 'No output recorded.', '', 'Checks and full evidence:', '', fence(attempt), '');
    }
  }
  return lines.join('\n') + '\n';
}

function attemptHtml(name, attempt) {
  return `<section class="attempt"><h3>${escape(name)}</h3><p><strong>${escape(attempt.quality)}</strong> · execution ${escape(attempt.executionStatus)} · model ${escape(attempt.identity.status)}</p><p class="muted">${escape(attempt.identity.reason)}</p><h4>Output</h4>${attempt.outputRecorded ? `<pre>${escape(display(attempt.output))}</pre>` : '<p>No output recorded.</p>'}<h4>Checks and reasons</h4><ul>${Object.entries(attempt.verdicts).map(([id, verdict]) => `<li><strong>${escape(id)}: ${escape(verdict.status)}</strong> — ${escape(verdict.reason)}</li>`).join('') || '<li>No recorded checks.</li>'}</ul><details><summary>Tool interactions, request receipts, costs and errors</summary><pre>${escape(json({ trace: attempt.trace, receipt: attempt.receipt, metrics: attempt.metrics, judge: attempt.judge, error: attempt.error }))}</pre></details></section>`;
}

export function htmlReport(comparison) {
  const summary = `<div class="scroll"><table><thead><tr>${headings.map(value => `<th>${value}</th>`).join('')}</tr></thead><tbody>${comparison.runs.map(run => `<tr>${summaryColumns(run).map(value => `<td>${escape(value)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  const pairs = comparison.pairs.map(pair => `<section class="pair" data-candidate="${escape(pair.candidateId)}"><h2>${escape(pair.candidateId)} against ${escape(comparison.baselineId)}</h2><p>${Object.entries(pair.counts).map(([name, count]) => `${escape(label(name))}: <strong>${count}</strong>`).join(' · ')}</p>${pair.rows.map(row => {
    const item = comparison.cases.find(value => value.id === row.caseId);
    return `<article class="case" data-category="${row.category}"><h2>${escape(row.title)}</h2><p>${escape(row.caseId)} · repetition ${row.repetition} · <strong>${escape(label(row.category))}</strong></p><details><summary>Input and expected outcome</summary><h4>Input</h4><pre>${escape(display(item.input))}</pre><h4>Expected</h4><pre>${escape(display(item.expected))}</pre></details><div class="columns">${attemptHtml(`Baseline: ${comparison.runs[0].requestedModel}`, row.baseline)}${attemptHtml(`Candidate: ${pair.candidateModel}`, row.candidate)}</div></article>`;
  }).join('')}</section>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'none'; img-src 'none'; form-action 'none'; base-uri 'none'"><title>Model comparison</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f7f8;color:#19303b;font:15px/1.5 system-ui,sans-serif}main{max-width:1400px;margin:auto;padding:28px}h1{font-size:32px;margin:0}h2{font-size:20px}h3{font-size:17px}h4{font-size:14px}.panel,.case{background:white;border:1px solid #d2dfe3;border-radius:10px;padding:22px;margin:20px 0}.muted{color:#596b75}.columns{display:grid;grid-template-columns:1fr 1fr;gap:18px}.attempt{min-width:0;padding-top:8px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f5f7fa;padding:14px;border:1px solid #dce4e9;border-radius:6px;max-height:500px;overflow:auto;font:12px/1.6 ui-monospace,monospace}table{border-collapse:collapse;width:100%;font-size:13px}td,th{padding:10px;border-bottom:1px solid #dce4e9;text-align:left;vertical-align:top}.scroll{overflow:auto}.toolbar{display:flex;gap:14px;flex-wrap:wrap;align-items:end}.toolbar label{display:grid;gap:5px;flex:1;min-width:160px}input,select,button{font:inherit;padding:8px;border:1px solid #a5b8bd;border-radius:6px;background:white;color:inherit}summary,button{cursor:pointer}.hidden{display:none!important}.notice{border-left:3px solid #aa7718;padding-left:14px}@media(max-width:760px){main{padding:14px}.columns{grid-template-columns:1fr}}@media print{body{background:white}main{padding:0}.toolbar{display:none}.hidden{display:block!important}pre{max-height:none}.case{break-inside:avoid}.columns{grid-template-columns:1fr 1fr}}
</style></head><body><main><h1>Compare models on the same eval</h1><p class="muted">Saved evidence only · baseline ${escape(comparison.baselineId)} · no inference or grading during report generation</p><section class="panel"><h2>Recorded results</h2>${summary}<p class="notice">Recorded checks retain failures and fallback outputs. Only pairs with complete, matching model receipts enter the improvement/regression counts. Unknown identity is not candidate success. Cost totals retain all observed spending and show attempt coverage; missing calls can hide missing cost.</p><details><summary>Scope, provenance and limitations</summary>${comparison.limitations.map(value => `<p>${escape(value)}</p>`).join('')}<pre>${escape(json({ workload: comparison.workload, fingerprint: comparison.fingerprint, criteria: comparison.criteria, sources: comparison.runs.map(run => ({ id: run.id, requestedModel: run.requestedModel, sourcePath: run.sourcePath, sourceDigest: run.sourceDigest, startedAt: run.startedAt, completedAt: run.completedAt, identity: run.identity, calls: run.callEvidence, taskLatency: run.applicationLatencyMs })) }))}</pre></details></section><section class="panel toolbar"><label>Candidate<select id="candidate">${comparison.pairs.map(pair => `<option value="${escape(pair.candidateId)}">${escape(pair.candidateId)} · ${escape(pair.candidateModel)}</option>`).join('')}</select></label><label>Outcome<select id="outcome"><option value="">All outcomes</option>${['regression', 'improvement', 'both_pass', 'both_fail', 'unscored', 'unverified_model', 'pending'].map(value => `<option value="${value}">${escape(label(value))}</option>`).join('')}</select></label><label>Search evidence<input id="search" type="search" placeholder="Case, output, tool or request"></label><button id="print">Print report</button><p id="count" role="status"></p></section>${pairs}</main><script>
function filter(){const candidate=document.querySelector('#candidate').value,outcome=document.querySelector('#outcome').value,search=document.querySelector('#search').value.toLowerCase();let visible=0,total=0;for(const pair of document.querySelectorAll('.pair')){const selected=pair.dataset.candidate===candidate;pair.classList.toggle('hidden',!selected);for(const card of pair.querySelectorAll('.case')){const matches=(!outcome||card.dataset.category===outcome)&&card.textContent.toLowerCase().includes(search);card.classList.toggle('hidden',!matches);if(selected){total++;if(matches)visible++;}}}document.querySelector('#count').textContent=visible+' of '+total+' attempts shown';}for(const id of ['candidate','outcome','search'])document.getElementById(id).addEventListener('input',filter);document.getElementById('print').addEventListener('click',()=>window.print());filter();
</script></body></html>`;
}
